// Code generated by entc, DO NOT EDIT.

package eventnameautofill

import (
	"entgo.io/ent/dialect/sql"
	"github.com/lbrictson/auditmon/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.EventNameAutofill {
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.EventNameAutofill {
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.EventNameAutofill {
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.EventNameAutofill {
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.EventNameAutofill {
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.EventNameAutofill {
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.EventNameAutofill {
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.EventNameAutofill {
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.EventNameAutofill {
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// EventName applies equality check predicate on the "eventName" field. It's identical to EventNameEQ.
func EventName(v string) predicate.EventNameAutofill {
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldEventName), v))
	})
}

// EventNameEQ applies the EQ predicate on the "eventName" field.
func EventNameEQ(v string) predicate.EventNameAutofill {
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldEventName), v))
	})
}

// EventNameNEQ applies the NEQ predicate on the "eventName" field.
func EventNameNEQ(v string) predicate.EventNameAutofill {
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldEventName), v))
	})
}

// EventNameIn applies the In predicate on the "eventName" field.
func EventNameIn(vs ...string) predicate.EventNameAutofill {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldEventName), v...))
	})
}

// EventNameNotIn applies the NotIn predicate on the "eventName" field.
func EventNameNotIn(vs ...string) predicate.EventNameAutofill {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldEventName), v...))
	})
}

// EventNameGT applies the GT predicate on the "eventName" field.
func EventNameGT(v string) predicate.EventNameAutofill {
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldEventName), v))
	})
}

// EventNameGTE applies the GTE predicate on the "eventName" field.
func EventNameGTE(v string) predicate.EventNameAutofill {
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldEventName), v))
	})
}

// EventNameLT applies the LT predicate on the "eventName" field.
func EventNameLT(v string) predicate.EventNameAutofill {
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldEventName), v))
	})
}

// EventNameLTE applies the LTE predicate on the "eventName" field.
func EventNameLTE(v string) predicate.EventNameAutofill {
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldEventName), v))
	})
}

// EventNameContains applies the Contains predicate on the "eventName" field.
func EventNameContains(v string) predicate.EventNameAutofill {
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldEventName), v))
	})
}

// EventNameHasPrefix applies the HasPrefix predicate on the "eventName" field.
func EventNameHasPrefix(v string) predicate.EventNameAutofill {
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldEventName), v))
	})
}

// EventNameHasSuffix applies the HasSuffix predicate on the "eventName" field.
func EventNameHasSuffix(v string) predicate.EventNameAutofill {
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldEventName), v))
	})
}

// EventNameEqualFold applies the EqualFold predicate on the "eventName" field.
func EventNameEqualFold(v string) predicate.EventNameAutofill {
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldEventName), v))
	})
}

// EventNameContainsFold applies the ContainsFold predicate on the "eventName" field.
func EventNameContainsFold(v string) predicate.EventNameAutofill {
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldEventName), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EventNameAutofill) predicate.EventNameAutofill {
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EventNameAutofill) predicate.EventNameAutofill {
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EventNameAutofill) predicate.EventNameAutofill {
	return predicate.EventNameAutofill(func(s *sql.Selector) {
		p(s.Not())
	})
}
