// Code generated by entc, DO NOT EDIT.

package event

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the event type in the database.
	Label = "event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "oid"
	// FieldEventTime holds the string denoting the event_time field in the database.
	FieldEventTime = "event_time"
	// FieldEventName holds the string denoting the event_name field in the database.
	FieldEventName = "event_name"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldResource holds the string denoting the resource field in the database.
	FieldResource = "resource"
	// FieldSourceIP holds the string denoting the source_ip field in the database.
	FieldSourceIP = "source_ip"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldReadOnly holds the string denoting the read_only field in the database.
	FieldReadOnly = "read_only"
	// FieldEventData holds the string denoting the event_data field in the database.
	FieldEventData = "event_data"
	// FieldEventSource holds the string denoting the event_source field in the database.
	FieldEventSource = "event_source"
	// Table holds the table name of the event in the database.
	Table = "events"
)

// Columns holds all SQL columns for event fields.
var Columns = []string{
	FieldID,
	FieldEventTime,
	FieldEventName,
	FieldUsername,
	FieldResource,
	FieldSourceIP,
	FieldRequestID,
	FieldReadOnly,
	FieldEventData,
	FieldEventSource,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultEventTime holds the default value on creation for the "event_time" field.
	DefaultEventTime time.Time
	// DefaultResource holds the default value on creation for the "resource" field.
	DefaultResource string
	// DefaultSourceIP holds the default value on creation for the "source_ip" field.
	DefaultSourceIP string
	// DefaultRequestID holds the default value on creation for the "request_id" field.
	DefaultRequestID string
	// DefaultReadOnly holds the default value on creation for the "read_only" field.
	DefaultReadOnly bool
	// DefaultEventSource holds the default value on creation for the "event_source" field.
	DefaultEventSource string
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
