// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lbrictson/auditmon/ent/eventnameautofill"
	"github.com/lbrictson/auditmon/ent/predicate"
)

// EventNameAutofillUpdate is the builder for updating EventNameAutofill entities.
type EventNameAutofillUpdate struct {
	config
	hooks    []Hook
	mutation *EventNameAutofillMutation
}

// Where appends a list predicates to the EventNameAutofillUpdate builder.
func (enau *EventNameAutofillUpdate) Where(ps ...predicate.EventNameAutofill) *EventNameAutofillUpdate {
	enau.mutation.Where(ps...)
	return enau
}

// SetEventName sets the "eventName" field.
func (enau *EventNameAutofillUpdate) SetEventName(s string) *EventNameAutofillUpdate {
	enau.mutation.SetEventName(s)
	return enau
}

// Mutation returns the EventNameAutofillMutation object of the builder.
func (enau *EventNameAutofillUpdate) Mutation() *EventNameAutofillMutation {
	return enau.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (enau *EventNameAutofillUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(enau.hooks) == 0 {
		affected, err = enau.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EventNameAutofillMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			enau.mutation = mutation
			affected, err = enau.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(enau.hooks) - 1; i >= 0; i-- {
			if enau.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = enau.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, enau.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (enau *EventNameAutofillUpdate) SaveX(ctx context.Context) int {
	affected, err := enau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (enau *EventNameAutofillUpdate) Exec(ctx context.Context) error {
	_, err := enau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (enau *EventNameAutofillUpdate) ExecX(ctx context.Context) {
	if err := enau.Exec(ctx); err != nil {
		panic(err)
	}
}

func (enau *EventNameAutofillUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   eventnameautofill.Table,
			Columns: eventnameautofill.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: eventnameautofill.FieldID,
			},
		},
	}
	if ps := enau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := enau.mutation.EventName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: eventnameautofill.FieldEventName,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, enau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{eventnameautofill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// EventNameAutofillUpdateOne is the builder for updating a single EventNameAutofill entity.
type EventNameAutofillUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EventNameAutofillMutation
}

// SetEventName sets the "eventName" field.
func (enauo *EventNameAutofillUpdateOne) SetEventName(s string) *EventNameAutofillUpdateOne {
	enauo.mutation.SetEventName(s)
	return enauo
}

// Mutation returns the EventNameAutofillMutation object of the builder.
func (enauo *EventNameAutofillUpdateOne) Mutation() *EventNameAutofillMutation {
	return enauo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (enauo *EventNameAutofillUpdateOne) Select(field string, fields ...string) *EventNameAutofillUpdateOne {
	enauo.fields = append([]string{field}, fields...)
	return enauo
}

// Save executes the query and returns the updated EventNameAutofill entity.
func (enauo *EventNameAutofillUpdateOne) Save(ctx context.Context) (*EventNameAutofill, error) {
	var (
		err  error
		node *EventNameAutofill
	)
	if len(enauo.hooks) == 0 {
		node, err = enauo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EventNameAutofillMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			enauo.mutation = mutation
			node, err = enauo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(enauo.hooks) - 1; i >= 0; i-- {
			if enauo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = enauo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, enauo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (enauo *EventNameAutofillUpdateOne) SaveX(ctx context.Context) *EventNameAutofill {
	node, err := enauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (enauo *EventNameAutofillUpdateOne) Exec(ctx context.Context) error {
	_, err := enauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (enauo *EventNameAutofillUpdateOne) ExecX(ctx context.Context) {
	if err := enauo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (enauo *EventNameAutofillUpdateOne) sqlSave(ctx context.Context) (_node *EventNameAutofill, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   eventnameautofill.Table,
			Columns: eventnameautofill.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: eventnameautofill.FieldID,
			},
		},
	}
	id, ok := enauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EventNameAutofill.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := enauo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, eventnameautofill.FieldID)
		for _, f := range fields {
			if !eventnameautofill.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != eventnameautofill.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := enauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := enauo.mutation.EventName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: eventnameautofill.FieldEventName,
		})
	}
	_node = &EventNameAutofill{config: enauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, enauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{eventnameautofill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
