// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/lbrictson/auditmon/ent/eventnameautofill"
)

// EventNameAutofill is the model entity for the EventNameAutofill schema.
type EventNameAutofill struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// EventName holds the value of the "eventName" field.
	EventName string `json:"eventName,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EventNameAutofill) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case eventnameautofill.FieldID:
			values[i] = new(sql.NullInt64)
		case eventnameautofill.FieldEventName:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type EventNameAutofill", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EventNameAutofill fields.
func (ena *EventNameAutofill) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case eventnameautofill.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ena.ID = int(value.Int64)
		case eventnameautofill.FieldEventName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field eventName", values[i])
			} else if value.Valid {
				ena.EventName = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this EventNameAutofill.
// Note that you need to call EventNameAutofill.Unwrap() before calling this method if this EventNameAutofill
// was returned from a transaction, and the transaction was committed or rolled back.
func (ena *EventNameAutofill) Update() *EventNameAutofillUpdateOne {
	return (&EventNameAutofillClient{config: ena.config}).UpdateOne(ena)
}

// Unwrap unwraps the EventNameAutofill entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ena *EventNameAutofill) Unwrap() *EventNameAutofill {
	tx, ok := ena.config.driver.(*txDriver)
	if !ok {
		panic("ent: EventNameAutofill is not a transactional entity")
	}
	ena.config.driver = tx.drv
	return ena
}

// String implements the fmt.Stringer.
func (ena *EventNameAutofill) String() string {
	var builder strings.Builder
	builder.WriteString("EventNameAutofill(")
	builder.WriteString(fmt.Sprintf("id=%v", ena.ID))
	builder.WriteString(", eventName=")
	builder.WriteString(ena.EventName)
	builder.WriteByte(')')
	return builder.String()
}

// EventNameAutofills is a parsable slice of EventNameAutofill.
type EventNameAutofills []*EventNameAutofill

func (ena EventNameAutofills) config(cfg config) {
	for _i := range ena {
		ena[_i].config = cfg
	}
}
