// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lbrictson/auditmon/ent/eventnameautofill"
)

// EventNameAutofillCreate is the builder for creating a EventNameAutofill entity.
type EventNameAutofillCreate struct {
	config
	mutation *EventNameAutofillMutation
	hooks    []Hook
}

// SetEventName sets the "eventName" field.
func (enac *EventNameAutofillCreate) SetEventName(s string) *EventNameAutofillCreate {
	enac.mutation.SetEventName(s)
	return enac
}

// Mutation returns the EventNameAutofillMutation object of the builder.
func (enac *EventNameAutofillCreate) Mutation() *EventNameAutofillMutation {
	return enac.mutation
}

// Save creates the EventNameAutofill in the database.
func (enac *EventNameAutofillCreate) Save(ctx context.Context) (*EventNameAutofill, error) {
	var (
		err  error
		node *EventNameAutofill
	)
	if len(enac.hooks) == 0 {
		if err = enac.check(); err != nil {
			return nil, err
		}
		node, err = enac.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EventNameAutofillMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = enac.check(); err != nil {
				return nil, err
			}
			enac.mutation = mutation
			if node, err = enac.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(enac.hooks) - 1; i >= 0; i-- {
			if enac.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = enac.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, enac.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (enac *EventNameAutofillCreate) SaveX(ctx context.Context) *EventNameAutofill {
	v, err := enac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (enac *EventNameAutofillCreate) Exec(ctx context.Context) error {
	_, err := enac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (enac *EventNameAutofillCreate) ExecX(ctx context.Context) {
	if err := enac.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (enac *EventNameAutofillCreate) check() error {
	if _, ok := enac.mutation.EventName(); !ok {
		return &ValidationError{Name: "eventName", err: errors.New(`ent: missing required field "EventNameAutofill.eventName"`)}
	}
	return nil
}

func (enac *EventNameAutofillCreate) sqlSave(ctx context.Context) (*EventNameAutofill, error) {
	_node, _spec := enac.createSpec()
	if err := sqlgraph.CreateNode(ctx, enac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (enac *EventNameAutofillCreate) createSpec() (*EventNameAutofill, *sqlgraph.CreateSpec) {
	var (
		_node = &EventNameAutofill{config: enac.config}
		_spec = &sqlgraph.CreateSpec{
			Table: eventnameautofill.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: eventnameautofill.FieldID,
			},
		}
	)
	if value, ok := enac.mutation.EventName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: eventnameautofill.FieldEventName,
		})
		_node.EventName = value
	}
	return _node, _spec
}

// EventNameAutofillCreateBulk is the builder for creating many EventNameAutofill entities in bulk.
type EventNameAutofillCreateBulk struct {
	config
	builders []*EventNameAutofillCreate
}

// Save creates the EventNameAutofill entities in the database.
func (enacb *EventNameAutofillCreateBulk) Save(ctx context.Context) ([]*EventNameAutofill, error) {
	specs := make([]*sqlgraph.CreateSpec, len(enacb.builders))
	nodes := make([]*EventNameAutofill, len(enacb.builders))
	mutators := make([]Mutator, len(enacb.builders))
	for i := range enacb.builders {
		func(i int, root context.Context) {
			builder := enacb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventNameAutofillMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, enacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, enacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, enacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (enacb *EventNameAutofillCreateBulk) SaveX(ctx context.Context) []*EventNameAutofill {
	v, err := enacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (enacb *EventNameAutofillCreateBulk) Exec(ctx context.Context) error {
	_, err := enacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (enacb *EventNameAutofillCreateBulk) ExecX(ctx context.Context) {
	if err := enacb.Exec(ctx); err != nil {
		panic(err)
	}
}
