// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lbrictson/auditmon/ent/predicate"
	"github.com/lbrictson/auditmon/ent/usernameautofill"
)

// UsernameAutofillDelete is the builder for deleting a UsernameAutofill entity.
type UsernameAutofillDelete struct {
	config
	hooks    []Hook
	mutation *UsernameAutofillMutation
}

// Where appends a list predicates to the UsernameAutofillDelete builder.
func (uad *UsernameAutofillDelete) Where(ps ...predicate.UsernameAutofill) *UsernameAutofillDelete {
	uad.mutation.Where(ps...)
	return uad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uad *UsernameAutofillDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(uad.hooks) == 0 {
		affected, err = uad.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UsernameAutofillMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uad.mutation = mutation
			affected, err = uad.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(uad.hooks) - 1; i >= 0; i-- {
			if uad.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = uad.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uad.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (uad *UsernameAutofillDelete) ExecX(ctx context.Context) int {
	n, err := uad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uad *UsernameAutofillDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: usernameautofill.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: usernameautofill.FieldID,
			},
		},
	}
	if ps := uad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, uad.driver, _spec)
}

// UsernameAutofillDeleteOne is the builder for deleting a single UsernameAutofill entity.
type UsernameAutofillDeleteOne struct {
	uad *UsernameAutofillDelete
}

// Exec executes the deletion query.
func (uado *UsernameAutofillDeleteOne) Exec(ctx context.Context) error {
	n, err := uado.uad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usernameautofill.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uado *UsernameAutofillDeleteOne) ExecX(ctx context.Context) {
	uado.uad.ExecX(ctx)
}
